version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  backend:
    image: node:16-alpine
    restart: always
    ports:
      - ${API_PORT}:3001
    depends_on:
      - db
    volumes:
      - .:/app/todo/api
    tty: true
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PORT=${DB_PORT}
      - HOSTNAME=db
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
