on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verify git repository
        uses: actions/checkout@v2

      - name: Install node on version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}

      - name: Generate Mocha report
        run: npm run test:result
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MOCHA Tests
          path: test-results.json
          reporter: mocha-json
