on: [pull_request]

jobs:
  Automatic-Tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: Todo_List_Test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Verify git repository
        uses: actions/checkout@v2

      - name: Install node on version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/Todo_List_Test'
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Generate Mocha report
        run: npm run test:result
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/Todo_List_Test'
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MOCHA Tests
          path: test-results.json
          reporter: mocha-json
